version: '3'
services:
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_USER: BDSME
      POSTGRES_PASSWORD: cse312
      POSTGRES_DB: BDSME
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://BDSME:cse312@db:5432/BDSME
      DOCKER_ENV: "docker"
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  pgdata:

