version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: BDSME
      POSTGRES_PASSWORD: cse312
      POSTGRES_DB: BDSME
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgres://BDSME:cse312@db:5432/BDSME
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  pgdata: