version: '3'
services:
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    environment:
      POSTGRES_USER: BDSME
      POSTGRES_PASSWORD: cse312
      POSTGRES_DB: BDSME
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://BDSME:cse312@db:5432/BDSME
      DOCKER_ENV: "docker"
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  pgdata:

